var express = require('express');
var router = express.Router();
var db = require('../db')

/* GET home page. */
router.get('/', function(req, res, next) {
  db.one('SELECT data FROM data')
    .then(function (result) {
      res.render('index', { data: "Query result: " + result.data })
    })
    .catch(function (error) {
      res.status(500).render('error', { error: error })
    })
});

/* GET api. */
router.get('/api', function(req, res, next) {
  db.one('SELECT data FROM data')
    .then(function (result) {
      res.send({ data: "Query result: " + result.data })
    })
    .catch(function (error) {
      res.status(500).send({ error: error })
    })
});

router.get('/health', function(req, res, next) {
  res.send({ health: "OK"})
});

/* GET create. */
router.get('/create', function(req, res, next) {
  db.any('CREATE TABLE IF NOT EXISTS data (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, data text NOT NULL);')
    .then(function () {
      db.any('INSERT INTO data(data) VALUES (\'Data from Postgres\');')
        .then(function () {
          res.render('index', { data: "OK! All set!"})
        })
        .catch(function (error) {
          res.render('error', { error: error })
        })
    })
    .catch(function (error) {
      res.status(500).render('error', { error: error })
    })
});

module.exports = router;
